const $=x=>document.getElementById(x),v=x=>$(x).value;let timer;
const cs=()=>[...document.querySelectorAll('.countries input:checked')].map(x=>x.value);
let t=new Date(),f=new Date();f.setMonth(f.getMonth()-1);$('to').value=t.toISOString().slice(0,10);$('from').value=f.toISOString().slice(0,10);
async function jf(url,opt={}){let r=await fetch(url,opt),txt=await r.text(),j;try{j=JSON.parse(txt)}catch{throw Error(txt||`HTTP ${r.status}`)}if(!r.ok)throw Error(j.detail||j.error||`HTTP ${r.status}`);return j}
fetch('/api/health').then(r=>r.json()).then(x=>$('health').textContent=x.r2?`● R2 online · ${x.workers} workers`:'● Storage unavailable');
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
function body(){return{from_date:v('from'),to_date:v('to'),countries:cs(),plan:v('plan'),strategy:v('strategy'),nth:+v('nth'),min_odds:+v('minOdds'),max_odds:+v('maxOdds'),min_runners:+v('minRunners'),max_runners:+v('maxRunners'),stake_mode:v('stakeMode'),amount:+v('amount'),commission:+v('commission')}}
$('run').onclick=async()=>{if(!cs().length)return alert('Select at least one country.');try{$('run').disabled=true;$('cached').classList.add('hide');$('job').classList.remove('hide');$('jobmsg').textContent='Submitting backtest…';let j=await jf('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body())});$('jobid').textContent='Job '+j.job_id;poll(j.job_id)}catch(e){fail(e.message)}};
async function poll(id){clearTimeout(timer);try{let j=await jf('/api/jobs/'+id);$('jobmsg').textContent=j.message||j.status;$('pct').textContent=(j.progress||0)+'%';$('bar').style.width=(j.progress||0)+'%';if(j.status==='complete'){render(await jf('/api/jobs/'+id+'/result'),j);$('run').disabled=false;return}if(j.status==='failed'){fail(j.message);return}timer=setTimeout(()=>poll(id),900)}catch(e){fail(e.message)}}
function fail(m){$('jobmsg').innerHTML='<span class="error">'+esc(m)+'</span>';$('title').textContent='Backtest could not complete';$('sub').textContent=m;$('run').disabled=false}
const money=x=>'£'+Number(x||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}),esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function render(r,j){let s=r.stats;$('title').textContent='Backtest complete';$('sub').textContent=`${r.request.from_date} → ${r.request.to_date} · ${r.request.countries.join(', ')} · ${r.request.strategy}`;$('cached').classList.toggle('hide',!j.cached);$('betsM').textContent=s.bets.toLocaleString();$('strikeM').textContent=s.strike.toFixed(2)+'%';$('netM').textContent=money(s.net);$('roiM').textContent=s.stake_roi.toFixed(2)+'%';$('ddM').textContent=money(s.max_drawdown);$('bspM').textContent=s.avg_bsp.toFixed(2);$('bandrows').innerHTML=r.bands.map(x=>`<tr><td>${x.band}</td><td>${x.bets}</td><td>${x.wins}</td><td>${x.strike.toFixed(2)}%</td><td>${money(x.gross)}</td><td>${money(x.net)}</td><td>${x.roi.toFixed(2)}%</td></tr>`).join('');$('betrows').innerHTML=r.bets.map(x=>`<tr><td>${esc(x.market_time)}</td><td>${esc(x.country)}</td><td>${esc(x.event_name)}</td><td>${esc(x.horse)}</td><td>${x.bsp.toFixed(2)}</td><td>${x.bet_type}</td><td>${x.won?'WIN':'LOSS'}</td><td>${money(x.net)}</td></tr>`).join('');$('trunc').textContent=r.bets_truncated?`Showing first ${r.bets.length.toLocaleString()} of ${r.total_bets.toLocaleString()} bets.`:'';$('detailgrid').innerHTML=[['Job ID',j.job_id],['Result cache',j.cached?'Persistent cache hit':'New calculation'],['Markets found',r.markets_found],['Markets skipped',r.skipped],['Elapsed',r.elapsed_seconds+' sec'],['Engine',r.engine_version]].map(x=>`<div><span>${x[0]}</span><b>${esc(x[1])}</b></div>`).join('');draw(s.equity)}
function draw(eq){$('empty').style.display=eq.length?'none':'block';let c=$('chart'),ctx=c.getContext('2d'),d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);if(!eq.length)return;let a=[0,...eq],mn=Math.min(...a),mx=Math.max(...a);if(mx===mn)mx=mn+1;ctx.strokeStyle='#2463eb';ctx.lineWidth=2;ctx.beginPath();a.forEach((z,i)=>{let x=38+(w-50)*i/(a.length-1||1),y=15+(h-50)*(mx-z)/(mx-mn);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}